name: "[v2] Generate Database and Deploy to Pages"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - v2
    paths:
      - "main.py"
      - "requirements.txt"
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  Build:
    name: Build Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: v2
      - name: Load secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Update JSON File with main.py and then commit
        shell: pwsh
        run: |
          try {
            python3 main.py
            git config --local user.email "nattadasu@nattadasu.my.id"
            git config --local user.name "Natsu Tadama"
            git add .
            git commit -m "Update JSON"
            git push
          }
          catch {
            write-host "No changes made"
          }

  DeployPages:
    needs: 'Build'
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v2
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Remove unwanted files
        shell: pwsh
        run: |
          Remove-Item ./.github -Recurse -Force
          Remove-Item ./.vscode -Recurse -Force
          $paths = @(
            "./.editorconfig",
            "./.gitattributes",
            "./.gitignore",
            "./aod.raw.json",
            "./arm.raw.json",
            "./ati.raw.json",
            "./kz.mapped.raw.json",
            "./kz.unknown.raw.json",
            "./kz.unmapped.raw.json",
            "./main.py",
            "./oo.raw.json",
            "./oo.unknown.raw.json",
            "./requirements.txt",
            "./sy.raw.json"
          )
          ForEach ($n in $paths) {
            Remove-Item $n -Force
          }
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
